# Generated by Django 6.0.2 on 2026-02-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_recipe_notes_recipestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnHandIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, help_text='Quantity of the ingredient currently on hand', null=True)),
                ('desired_quantity', models.FloatField(blank=True, help_text='Desired quantity of the ingredient to have on hand (e.g., for meal planning)', null=True)),
                ('warning_quantity', models.FloatField(blank=True, help_text='Optional warning threshold quantity (e.g., if quantity on hand falls below this, issue a warning)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the ingredient on hand')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_hand_ingredients', to='api.ingredient')),
            ],
        ),
    ]
