// Semi-generated by Sonnet 4.6, edited and modified/fixed by hand
import { useState, useEffect, useMemo, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Refrigerator } from 'lucide-react';
import { useQueryClient } from '@tanstack/react-query';
import {
  useIngredientsRetrieve,
  useRecipesList,
  useIngredientStoreCreate,
  useIngredientStorePartialUpdate,
  getIngredientsRetrieveQueryKey,
} from '../api/mealmodeAPI';
import type { Ingredient, OnHandIngredient } from '../api/mealmodeAPI';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { NutritionLabel } from '../components/nutritionLabel';
import { RecipeCard } from '../components/recipecard';
import { multiplyNutritionStats } from '../utils/calculations';
import { fetchAllPages } from '../utils/api';
import { Card } from '../components/ui/card';

type OnHandFormValues = {
  quantity: string;
  desired_quantity: string;
  warning_quantity: string;
  notes: string;
};

function onHandToFormValues(oh: OnHandIngredient | null | undefined): OnHandFormValues {
  return {
    quantity: oh?.quantity == null ? '' : String(oh.quantity),
    desired_quantity: oh?.desired_quantity == null ? '' : String(oh.desired_quantity),
    warning_quantity: oh?.warning_quantity == null ? '' : String(oh.warning_quantity),
    notes: oh?.notes ?? '',
  };
}

function parseOpt(v: string): number | null {
  const n = Number.parseFloat(v);
  return Number.isNaN(n) ? null : n;
}

function OnHandForm({
  ingredient,
  ingredientId,
  existing,
  onSaved,
}: {
  readonly ingredient: Ingredient;
  readonly ingredientId: number;
  readonly existing: OnHandIngredient | null | undefined;
  readonly onSaved: () => void;
}) {
  const [values, setValues] = useState<OnHandFormValues>(() => onHandToFormValues(existing));
  const [editing, setEditing] = useState(!existing);

  useEffect(() => {
    setValues(onHandToFormValues(existing));
    setEditing(!existing);
  }, [existing]);

  const createMutation = useIngredientStoreCreate();
  const patchMutation = useIngredientStorePartialUpdate();
  const isPending = createMutation.isPending || patchMutation.isPending;

  const handleSave = useCallback(() => {
    const payload = {
      quantity: parseOpt(values.quantity),
      desired_quantity: parseOpt(values.desired_quantity),
      warning_quantity: parseOpt(values.warning_quantity),
      notes: values.notes,
    };
    if (existing) {
      patchMutation.mutate({ id: existing.id, data: payload }, { onSuccess: () => { setEditing(false); onSaved(); } });
    } else {
      createMutation.mutate({ data: { ...payload, ingredient: ingredientId } }, { onSuccess: () => { setEditing(false); onSaved(); } });
    }
  }, [values, existing, ingredientId, onSaved, createMutation, patchMutation]);

  function field(label: string, key: keyof OnHandFormValues, unit?: string) {
    return (
      <div className="flex items-center gap-2">
        <label className="w-36 text-sm shrink-0">{label}</label>
        {editing ? (
          <div className="flex items-center gap-2 flex-1">
            <Input
              type="number"
              min={0}
              value={values[key]}
              onChange={e => setValues(v => ({ ...v, [key]: e.target.value }))}
              className="flex-1"
            />
            <div>{unit}</div>
          </div>
        ) : (
          <span className="text-sm font-medium">{values[key] === '' ? '—' : `${values[key]}${unit ?? ''}`}</span>
        )}
      </div>
    );
  }

  return (
    <Card className="p-4 space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="font-semibold flex items-center gap-2">
          <Refrigerator className="w-4 h-4" /> On-Hand
        </h3>
        {!editing && (
          <Button variant="outline" size="sm" onClick={() => setEditing(true)}>Edit</Button>
        )}
      </div>
      {field('Quantity on hand', 'quantity', ingredient.nutrition_stats?.base_unit)}
      {field('Desired quantity', 'desired_quantity', ingredient.nutrition_stats?.base_unit)}
      {field('Warning below', 'warning_quantity', ingredient.nutrition_stats?.base_unit)}
      <div className="flex items-center gap-2">
        <label htmlFor="on-hand-notes" className="w-36 text-sm shrink-0">Notes</label>
        {editing ? (
          <Input
            id="on-hand-notes"
            value={values.notes}
            onChange={e => setValues(v => ({ ...v, notes: e.target.value }))}
            className="flex-1"
          />
        ) : (
          <span className="text-sm font-medium">{values.notes || '—'}</span>
        )}
      </div>
      {editing && (
        <div className="flex gap-2 pt-1">
          <Button size="sm" onClick={handleSave} disabled={isPending}>
            {isPending ? 'Saving…' : 'Save'}
          </Button>
          {existing && (
            <Button size="sm" variant="outline" onClick={() => { setEditing(false); setValues(onHandToFormValues(existing)); }}>
              Cancel
            </Button>
          )}
        </div>
      )}
    </Card>
  );
}

export function IngredientPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const numericId = id == null ? Number.NaN : Number(id);
  const validId = !Number.isNaN(numericId) && numericId > 0;

  const { data, isLoading, isError } = useIngredientsRetrieve(
    validId ? numericId : 0,
    { query: { enabled: validId } }
  );
  const ingredient = data?.data;

  const { data: recipesData } = useRecipesList(undefined, { query: { enabled: validId } });
  const [allRecipes, setAllRecipes] = useState<NonNullable<typeof recipesData>['data']['results']>([]);

  useEffect(() => {
    if (recipesData) {
      fetchAllPages<NonNullable<typeof recipesData>['data']['results'][number]>(recipesData)
        .then(r => setAllRecipes(r));
    }
  }, [recipesData]);

  const usedInRecipes = useMemo(
    () => allRecipes.filter(r => r.ingredients_list.some(ri => ri.ingredient.id === numericId)),
    [allRecipes, numericId]
  );

  function invalidateIngredient() {
    queryClient.invalidateQueries({ queryKey: getIngredientsRetrieveQueryKey(numericId) });
  }

  if (!validId) {
    return (
      <div className="text-center py-12">
        <p className="text-palette-taupe">Invalid ingredient</p>
        <Button onClick={() => navigate(-1)} className="mt-4">Go back</Button>
      </div>
    );
  }

  if (isLoading) {
    return <div className="text-center py-12 text-palette-slate">Loading…</div>;
  }

  if (isError || !ingredient) {
    return (
      <div className="text-center py-12">
        <p className="text-palette-taupe">Ingredient not found</p>
        <Button onClick={() => navigate(-1)} className="mt-4">Go back</Button>
      </div>
    );
  }

  const stats = ingredient.nutrition_stats;
  const unit = stats?.base_unit ?? 'unit';
  const aggregatedStats = stats ? multiplyNutritionStats(stats, 1) : null;

  return (
    <div className="space-y-6">
      <Button variant="ghost" onClick={() => navigate(-1)} className="-ml-2">
        <ArrowLeft className="w-4 h-4 mr-2" />
        Back
      </Button>

      <h2 className="text-2xl font-semibold text-palette-taupe">{ingredient.name}</h2>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Left column */}
        <div className="space-y-4">
          <OnHandForm
            ingredient={ingredient}
            ingredientId={numericId}
            existing={ingredient.on_hand}
            onSaved={invalidateIngredient}
          />
          <h3 className="font-semibold text-lg">Used in recipes</h3>
          {usedInRecipes.length === 0 ? (
            <p className="text-sm text-palette-slate">Not used in any recipes.</p>
          ) : (
            usedInRecipes.map(recipe => (
              <RecipeCard key={recipe.id} recipe={recipe} />
            ))
          )}
        </div>

        {/* <div className="space-y-3">
        </div>
        Right column — recipes */}
        {aggregatedStats && (
          <Card className="p-4">
            <NutritionLabel nutritionStats={aggregatedStats} per_unit={unit} />
          </Card>
        )}
      </div>
    </div>
  );
}
