/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Mealmode API
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

/**
 * * `kg` - Kilogram
* `L` - Liter
* `pc` - Piece / Count
 */
export type BaseUnitEnum = typeof BaseUnitEnum[keyof typeof BaseUnitEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BaseUnitEnum = {
  kg: 'kg',
  L: 'L',
  pc: 'pc',
} as const;

export interface Ingredient {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  readonly nutrition_stats: NutritionStats;
}

export interface NutritionStats {
  readonly id: number;
  /** The base unit for the nutrition stats (e.g., per kg, per liter, etc.)

* `kg` - Kilogram
* `L` - Liter
* `pc` - Piece / Count */
  base_unit?: BaseUnitEnum;
  /**
   * Calories (Kcal) per base unit
   * @nullable
   */
  kcal_per_unit?: number | null;
  /**
   * Saturated fat (g) per base unit
   * @nullable
   */
  fat_saturated_grams_per_unit?: number | null;
  /**
   * Trans fat (g) per base unit
   * @nullable
   */
  fat_trans_grams_per_unit?: number | null;
  /**
   * Fiber (g) per base unit
   * @nullable
   */
  carbohydrate_fiber_grams_per_unit?: number | null;
  /**
   * Sugars (g) per base unit
   * @nullable
   */
  carbohydrate_sugar_grams_per_unit?: number | null;
  /**
   * Protein (g) per base unit
   * @nullable
   */
  protein_grams_per_unit?: number | null;
  /**
   * Cholesterol (mg) per base unit
   * @nullable
   */
  cholesterol_milligrams_per_unit?: number | null;
  /**
   * Sodium (mg) per base unit
   * @nullable
   */
  sodium_milligrams_per_unit?: number | null;
  /**
   * Potassium (mg) per base unit
   * @nullable
   */
  potassium_milligrams_per_unit?: number | null;
  /**
   * Calcium (mg) per base unit
   * @nullable
   */
  calcium_milligrams_per_unit?: number | null;
  /**
   * Iron (mg) per base unit
   * @nullable
   */
  iron_milligrams_per_unit?: number | null;
  /**
   * Vitamin A (mg) per base unit
   * @nullable
   */
  vitamin_a_milligrams_per_unit?: number | null;
  /**
   * Vitamin C (mg) per base unit
   * @nullable
   */
  vitamin_c_milligrams_per_unit?: number | null;
  /**
   * Vitamin D (mg) per base unit
   * @nullable
   */
  vitamin_d_milligrams_per_unit?: number | null;
  /** @nullable */
  ingredient?: number | null;
}

export interface PaginatedIngredientList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Ingredient[];
}

export interface PaginatedRecipeList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: Recipe[];
}

export interface PatchedIngredient {
  readonly id?: number;
  /** @maxLength 100 */
  name?: string;
  readonly nutrition_stats?: NutritionStats;
}

export interface PatchedRecipe {
  readonly id?: number;
  /** @maxLength 100 */
  name?: string;
  readonly ingredients_list?: readonly RecipeIngredient[];
}

export interface Recipe {
  readonly id: number;
  /** @maxLength 100 */
  name: string;
  readonly ingredients_list: readonly RecipeIngredient[];
}

export interface RecipeIngredient {
  readonly id: number;
  readonly ingredient: Ingredient;
  /** Quantity in base units (e.g., grams, liters, pieces), defined by the ingredient's nutrition stats) */
  quantity: number;
}

export type IngredientsListParams = {
/**
 * Number of results to return per page.
 */
limit?: number;
/**
 * The initial index from which to return the results.
 */
offset?: number;
};

export type RecipesListParams = {
/**
 * Number of results to return per page.
 */
limit?: number;
/**
 * The initial index from which to return the results.
 */
offset?: number;
};

export const ingredientsList = <TData = AxiosResponse<PaginatedIngredientList>>(
    params?: IngredientsListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/ingredients/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const ingredientsCreate = <TData = AxiosResponse<Ingredient>>(
    ingredient: NonReadonly<Ingredient>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/ingredients/`,
      ingredient,options
    );
  }

export const ingredientsRetrieve = <TData = AxiosResponse<Ingredient>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/ingredients/${id}/`,options
    );
  }

export const ingredientsUpdate = <TData = AxiosResponse<Ingredient>>(
    id: number,
    ingredient: NonReadonly<Ingredient>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/ingredients/${id}/`,
      ingredient,options
    );
  }

export const ingredientsPartialUpdate = <TData = AxiosResponse<Ingredient>>(
    id: number,
    patchedIngredient: NonReadonly<PatchedIngredient>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/api/ingredients/${id}/`,
      patchedIngredient,options
    );
  }

export const ingredientsDestroy = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/ingredients/${id}/`,options
    );
  }

export const recipesList = <TData = AxiosResponse<PaginatedRecipeList>>(
    params?: RecipesListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/recipes/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export const recipesCreate = <TData = AxiosResponse<Recipe>>(
    recipe: NonReadonly<Recipe>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/recipes/`,
      recipe,options
    );
  }

export const recipesRetrieve = <TData = AxiosResponse<Recipe>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/recipes/${id}/`,options
    );
  }

export const recipesUpdate = <TData = AxiosResponse<Recipe>>(
    id: number,
    recipe: NonReadonly<Recipe>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/recipes/${id}/`,
      recipe,options
    );
  }

export const recipesPartialUpdate = <TData = AxiosResponse<Recipe>>(
    id: number,
    patchedRecipe: NonReadonly<PatchedRecipe>, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/api/recipes/${id}/`,
      patchedRecipe,options
    );
  }

export const recipesDestroy = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/recipes/${id}/`,options
    );
  }

export type IngredientsListResult = AxiosResponse<PaginatedIngredientList>
export type IngredientsCreateResult = AxiosResponse<Ingredient>
export type IngredientsRetrieveResult = AxiosResponse<Ingredient>
export type IngredientsUpdateResult = AxiosResponse<Ingredient>
export type IngredientsPartialUpdateResult = AxiosResponse<Ingredient>
export type IngredientsDestroyResult = AxiosResponse<void>
export type RecipesListResult = AxiosResponse<PaginatedRecipeList>
export type RecipesCreateResult = AxiosResponse<Recipe>
export type RecipesRetrieveResult = AxiosResponse<Recipe>
export type RecipesUpdateResult = AxiosResponse<Recipe>
export type RecipesPartialUpdateResult = AxiosResponse<Recipe>
export type RecipesDestroyResult = AxiosResponse<void>
