FROM ghcr.io/astral-sh/uv:alpine

RUN apk add --no-cache tzdata
WORKDIR /app/backend
COPY pyproject.toml uv.lock* ./
RUN uv sync --frozen
COPY src/backend .

EXPOSE 8000
CMD ["uv", "run", "manage.py", "runserver", "0.0.0.0:8000"]