# Generated by Django 6.0.2 on 2026-02-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece / Count')], default='kg', help_text='The base unit for the nutrition stats (e.g., per kg, per liter, etc.)', max_length=4)),
                ('kcal_per_unit', models.FloatField(null=True)),
                ('fat_saturated_per_unit', models.FloatField(null=True)),
                ('fat_trans_per_unit', models.FloatField(null=True)),
                ('carbohydrate_fiber_per_unit', models.FloatField(null=True)),
                ('carbohydrate_sugar_per_unit', models.FloatField(null=True)),
                ('protein_per_unit', models.FloatField(null=True)),
                ('cholesterol_per_unit', models.FloatField(null=True)),
                ('sodium_per_unit', models.FloatField(null=True)),
                ('potassium_per_unit', models.FloatField(null=True)),
                ('calcium_per_unit', models.FloatField(null=True)),
                ('iron_per_unit', models.FloatField(null=True)),
                ('vitamin_a_per_unit', models.FloatField(null=True)),
                ('vitamin_c_per_unit', models.FloatField(null=True)),
                ('vitamin_d_per_unit', models.FloatField(null=True)),
                ('ingredient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_stats', to='api.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('l', 'Liter'), ('pc', 'Piece / Count')], default='kg', help_text='The unit multiplier for the ingredient quantity (e.g., kg, liter, piece, etc.)', max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='api.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='api.RecipeIngredient', to='api.ingredient'),
        ),
    ]
