# Generated by Django 6.0.2 on 2026-02-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(help_text="Quantity in base units (e.g., grams, liters, pieces), defined by the ingredient's nutrition stats)"),
        ),
    ]
