# Generated by Django 6.0.2 on 2026-02-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='calcium_per_unit',
            new_name='calcium_milligrams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='carbohydrate_fiber_per_unit',
            new_name='carbohydrate_fiber_grams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='carbohydrate_sugar_per_unit',
            new_name='carbohydrate_sugar_grams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='cholesterol_per_unit',
            new_name='cholesterol_grams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='fat_saturated_per_unit',
            new_name='fat_saturated_grams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='fat_trans_per_unit',
            new_name='fat_trans_grams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='iron_per_unit',
            new_name='iron_milligrams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='potassium_per_unit',
            new_name='potassium_milligrams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='protein_per_unit',
            new_name='protein_grams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='sodium_per_unit',
            new_name='sodium_milligrams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='vitamin_a_per_unit',
            new_name='vitamin_a_milligrams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='vitamin_c_per_unit',
            new_name='vitamin_c_milligrams_per_unit',
        ),
        migrations.RenameField(
            model_name='nutritionstats',
            old_name='vitamin_d_per_unit',
            new_name='vitamin_d_milligrams_per_unit',
        ),
    ]
