# Generated by Django 6.0.2 on 2026-02-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_calcium_per_unit_nutritionstats_calcium_milligrams_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionstats',
            name='cholesterol_grams_per_unit',
        ),
        migrations.AddField(
            model_name='nutritionstats',
            name='cholesterol_milligrams_per_unit',
            field=models.FloatField(blank=True, help_text='Cholesterol (mg) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='calcium_milligrams_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='carbohydrate_fiber_grams_per_unit',
            field=models.FloatField(blank=True, help_text='Fiber (g) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='carbohydrate_sugar_grams_per_unit',
            field=models.FloatField(blank=True, help_text='Sugars (g) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='fat_saturated_grams_per_unit',
            field=models.FloatField(blank=True, help_text='Saturated fat (g) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='fat_trans_grams_per_unit',
            field=models.FloatField(blank=True, help_text='Trans fat (g) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='iron_milligrams_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='kcal_per_unit',
            field=models.FloatField(blank=True, help_text='Calories (Kcal) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='potassium_milligrams_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='protein_grams_per_unit',
            field=models.FloatField(blank=True, help_text='Protein (g) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='sodium_milligrams_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='vitamin_a_milligrams_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='vitamin_c_milligrams_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='vitamin_d_milligrams_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
