# Generated by Django 6.0.2 on 2026-02-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_recipeingredient_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1, help_text='Number of servings this recipe makes'),
        ),
    ]
