# Generated by Django 6.0.2 on 2026-02-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_nutritionstats_cholesterol_grams_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionstats',
            name='calcium_milligrams_per_unit',
            field=models.FloatField(blank=True, help_text='Calcium (mg) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='iron_milligrams_per_unit',
            field=models.FloatField(blank=True, help_text='Iron (mg) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='potassium_milligrams_per_unit',
            field=models.FloatField(blank=True, help_text='Potassium (mg) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='sodium_milligrams_per_unit',
            field=models.FloatField(blank=True, help_text='Sodium (mg) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='vitamin_a_milligrams_per_unit',
            field=models.FloatField(blank=True, help_text='Vitamin A (mg) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='vitamin_c_milligrams_per_unit',
            field=models.FloatField(blank=True, help_text='Vitamin C (mg) per base unit', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionstats',
            name='vitamin_d_milligrams_per_unit',
            field=models.FloatField(blank=True, help_text='Vitamin D (mg) per base unit', null=True),
        ),
    ]
