# Generated by Django 6.0.2 on 2026-02-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipe_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='lowest_cost',
            field=models.FloatField(blank=True, help_text='Lowest known cost per base unit (e.g., $/kg', null=True),
        ),
    ]
