# Generated by Django 6.0.2 on 2026-02-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_nutritionstats_calcium_milligrams_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionstats',
            name='base_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('L', 'Liter'), ('pc', 'Piece / Count')], default='kg', help_text='The base unit for the nutrition stats (e.g., per kg, per liter, etc.)', max_length=4),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('L', 'Liter'), ('pc', 'Piece / Count')], default='kg', help_text='The unit multiplier for the ingredient quantity (e.g., kg, liter, piece, etc.)', max_length=4),
        ),
    ]
