# Generated by Django 6.0.2 on 2026-02-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recipetag_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time_minutes',
            field=models.FloatField(blank=True, help_text='Preparation time in minutes', null=True),
        ),
    ]
