# Generated by Django 6.0.2 on 2026-02-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_recipe_prep_time_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time_minutes',
            field=models.FloatField(blank=True, help_text='Cooking time in minutes', null=True),
        ),
    ]
