# Generated by Django 6.0.2 on 2026-02-21 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_recipe_notes_recipestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(help_text='Day of week, e.g. monday, tuesday', max_length=20)),
                ('slot', models.CharField(help_text='Meal slot, e.g. breakfast, lunch, dinner', max_length=20)),
                ('servings', models.IntegerField(default=1)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_entries', to='api.recipe')),
            ],
            options={
                'verbose_name_plural': 'meal plan entries',
                'ordering': ['day', 'slot'],
            },
        ),
    ]
