# Generated by Django 6.0.2 on 2026-02-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='lowest_cost',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='estimated_cost',
            field=models.FloatField(blank=True, help_text='Estimated per base unit (e.g., $/kg), used as a fallback if no on-hand cost data is available', null=True),
        ),
    ]
