# Generated by Django 6.0.2 on 2026-02-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_meal_plan_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplanentry',
            name='day',
            field=models.CharField(help_text='Day of the week, e.g. monday, tuesday', max_length=20),
        ),
    ]
