# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_mealplanentry_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplanentry",
            name="day",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                help_text="Day of the week",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mealplanentry",
            name="slot",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("snack", "Snack"),
                ],
                help_text="Meal slot (e.g. breakfast, lunch, dinner)",
                max_length=20,
            ),
        ),
    ]
