# Generated by Django 6.0.2 on 2026-02-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_ingredient_lowest_cost_and_more'),
        ('api', '0011_meal_plan_entry_enum_fields'),
    ]

    operations = [
    ]
