# Generated by Django 6.0.2 on 2026-02-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_ingredientalias_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional URL to an image of the dish'),
        ),
    ]
