# Generated by Django 6.0.2 on 2026-02-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional URL to an image of the dish', max_length=512),
        ),
    ]
