# Generated by Django 6.0.2 on 2026-02-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_url_source_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='code',
            new_name='url',
        ),
        migrations.AddField(
            model_name='source',
            name='cached_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
