# Generated by Django 6.0.2 on 2026-02-21 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_rename_code_source_url_source_cached_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='scraper',
        ),
        migrations.AddField(
            model_name='scraper',
            name='cached_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='cached_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.source'),
        ),
        migrations.AddField(
            model_name='scraper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
