# Generated by Django 6.0.2 on 2026-02-21 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_source_scraper_scraper_cached_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='cached_source',
        ),
        migrations.AddField(
            model_name='scraper',
            name='cached_url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for', to='scraper.source'),
        ),
        migrations.AddField(
            model_name='source',
            name='scraper',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='scraper.scraper'),
            preserve_default=False,
        ),
    ]
