# Generated by Django 6.0.2 on 2026-02-21 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_remove_scraper_cached_source_scraper_cached_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='scraper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='scraper.scraper'),
        ),
    ]
