# Generated by Django 6.0.2 on 2026-02-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_source_scraper'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('L', 'Liter'), ('pc', 'Piece / Count')], default='kg', help_text='The base unit for the Source stats (e.g., per kg, per liter, etc.)', max_length=4),
        ),
    ]
