# Generated by Django 6.0.2 on 2026-02-22 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_rename_cached_url_scraper_cached_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='cached_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='cached_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for', to='scraper.source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='cached_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
