# Generated by Django 6.0.2 on 2026-02-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260222_0016'),
        ('scraper', '0009_alter_scraper_cached_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='ingredient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraper', to='api.ingredient'),
        ),
    ]
