# Generated by Django 6.0.2 on 2026-02-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_scraper_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='cached_error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
