# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0012_confirmablerecipe_confirmablerecipeingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.CharField(max_length=500),
        ),
    ]
